services:
  app:
    user: ${UID}:${GID}
    build:
      context: .
      target: runner
      args:
        - UID=${UID}
        - GID=${GID}
    image: henrotaym/laravel-package-scaffolder-runner:local
    volumes:
      - ./:/opt/apps/app
    ports:
      - ${VITE_PORT:-8000}:${VITE_PORT:-8000}

  cli:
    user: ${UID}:${GID}
    build:
      context: .
      target: cli
      args:
        - UID=${UID}
        - GID=${GID}
    image: henrotaym/laravel-package-scaffolder-cli:local
    volumes:
      - ./:/opt/apps/app
    profiles:
      - cli

  bun:
    user: ${UID}:${GID}
    build:
      context: .
      target: bun
    image: henrotaym/laravel-package-scaffolder-bun:local
    volumes:
      - ./:/opt/apps/app
    profiles:
      - cli
