name: Linter

on:
  push:
    branches:
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun lint
